@port = {{$processEnv PORT}}
@hostname = {{$processEnv HOSTNAME}}

http://{{hostname}}:{{port}}/question
###
http://{{hostname}}:{{port}}/quiz
###
http://{{hostname}}:{{port}}/score
###
http://{{hostname}}:{{port}}/tag
###
http://{{hostname}}:{{port}}/token
###
http://{{hostname}}:{{port}}/user